// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod example {
    pub mod greeter {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod greet {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_greet_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result1 = {
          let len0 = arg1;
          let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
          T_::greet(_rt::string_lift(bytes0))
        };
        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
        let vec3 = (result1.into_bytes()).into_boxed_slice();
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        ::core::mem::forget(vec3);
        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
        *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
        ptr2
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_greet<T_: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
      } }
      pub trait Guest {
        #[allow(async_fn_in_trait)]
        fn greet(name: _rt::String,) -> _rt::String;
      }
      #[doc(hidden)]

      macro_rules! __export_example_greeter_greet_0_1_0_cabi{
        ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          #[unsafe(export_name = "example:greeter/greet@0.1.0#greet")]
          unsafe extern "C" fn export_greet(arg0: *mut u8,arg1: usize,) -> *mut u8 {
            unsafe { $($path_to_types)*::_export_greet_cabi::<$ty>(arg0, arg1) }
          }
          #[unsafe(export_name = "cabi_post_example:greeter/greet@0.1.0#greet")]
          unsafe extern "C" fn _post_return_greet(arg0: *mut u8,) {
            unsafe { $($path_to_types)*::__post_return_greet::<$ty>(arg0) }
          }
        };);
      }
      #[doc(hidden)]
      pub(crate) use __export_example_greeter_greet_0_1_0_cabi;

      #[cfg_attr(target_pointer_width="64", repr(align(8)))]
      #[cfg_attr(target_pointer_width="32", repr(align(4)))]
      struct _RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
      static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);

    }

  }
}
pub mod wasi {
  pub mod cli {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod run {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::super::_rt;
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_run_cabi<T_: Guest>() -> i32 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T_::run()
      };
      let result1 = match result0 {
        Ok(_) => { 0i32 },
        Err(_) => { 1i32 },
      };result1
    } }
    pub trait Guest {
      /// Run the program.
      #[allow(async_fn_in_trait)]
      fn run() -> Result<(),()>;
    }
    #[doc(hidden)]

    macro_rules! __export_wasi_cli_run_0_2_7_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "wasi:cli/run@0.2.7#run")]
        unsafe extern "C" fn export_run() -> i32 {
          unsafe { $($path_to_types)*::_export_run_cabi::<$ty>() }
        }
      };);
    }
    #[doc(hidden)]
    pub(crate) use __export_wasi_cli_run_0_2_7_cabi;

  }

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::string::String;
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_greeter_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::example::greeter::greet::__export_example_greeter_greet_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::example::greeter::greet);
  $($path_to_types_root)*::exports::wasi::cli::run::__export_wasi_cli_run_0_2_7_cabi!($ty with_types_in $($path_to_types_root)*::exports::wasi::cli::run);
  )
}
#[doc(inline)]
pub(crate) use __export_greeter_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.53.1:example:greeter@0.1.0:greeter:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 265] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8b\x01\x01A\x02\x01\
A\x04\x01B\x02\x01@\x01\x04names\0s\x04\0\x05greet\x01\0\x04\0\x1bexample:greete\
r/greet@0.1.0\x05\0\x01B\x03\x01j\0\0\x01@\0\0\0\x04\0\x03run\x01\x01\x04\0\x12w\
asi:cli/run@0.2.7\x05\x01\x04\0\x1dexample:greeter/greeter@0.1.0\x04\0\x0b\x0d\x01\
\0\x07greeter\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.245.1\x10wit-bindgen-rust\x060.53.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

