// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod demo {
    pub mod statistics {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod statistics {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            pub fn mean(numbers: &[f64]) -> f64 {
                unsafe {
                    let vec0 = numbers;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "demo:statistics/statistics@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "mean"]
                        fn wit_import1(_: *mut u8, _: usize) -> f64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> f64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
                    ret
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn standard_deviation(numbers: &[f64]) -> f64 {
                unsafe {
                    let vec0 = numbers;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "demo:statistics/statistics@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "standard-deviation"]
                        fn wit_import1(_: *mut u8, _: usize) -> f64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> f64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
                    ret
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn median(numbers: &[f64]) -> f64 {
                unsafe {
                    let vec0 = numbers;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "demo:statistics/statistics@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "median"]
                        fn wit_import1(_: *mut u8, _: usize) -> f64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> f64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
                    ret
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn variance(numbers: &[f64]) -> f64 {
                unsafe {
                    let vec0 = numbers;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "demo:statistics/statistics@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "variance"]
                        fn wit_import1(_: *mut u8, _: usize) -> f64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> f64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
                    ret
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn range(numbers: &[f64]) -> f64 {
                unsafe {
                    let vec0 = numbers;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "demo:statistics/statistics@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "range"]
                        fn wit_import1(_: *mut u8, _: usize) -> f64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> f64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
                    ret
                }
            }
        }
    }
}
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:demo:runner@0.1.0:runner:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 283] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9e\x01\x01A\x02\x01\
A\x02\x01B\x07\x01pu\x01@\x01\x07numbers\0\0u\x04\0\x04mean\x01\x01\x04\0\x12sta\
ndard-deviation\x01\x01\x04\0\x06median\x01\x01\x04\0\x08variance\x01\x01\x04\0\x05\
range\x01\x01\x03\0\x20demo:statistics/statistics@0.1.0\x05\0\x04\0\x18demo:runn\
er/runner@0.1.0\x04\0\x0b\x0c\x01\0\x06runner\x03\0\0\0G\x09producers\x01\x0cpro\
cessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
